"""ilk migration - bolge afet_olayi tahmin_kaydi tablolari

Revision ID: 4671f1fcffb4
Revises: 
Create Date: 2026-05-28 22:32:36.315970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4671f1fcffb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolgeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('il', sa.String(length=50), nullable=False),
    sa.Column('ilce', sa.String(length=50), nullable=True),
    sa.Column('nufus', sa.Integer(), nullable=False),
    sa.Column('koordinat_lat', sa.Float(), nullable=True),
    sa.Column('koordinat_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('afet_olaylari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bolge_id', sa.Integer(), nullable=False),
    sa.Column('deprem_buyuklugu', sa.Float(), nullable=False),
    sa.Column('bina_yikim_orani', sa.Float(), nullable=False),
    sa.Column('hava_sicakligi', sa.Float(), nullable=False),
    sa.Column('ulasim_durumu', sa.Integer(), nullable=False),
    sa.Column('yasli_nufus_orani', sa.Float(), nullable=False),
    sa.Column('olay_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bolge_id'], ['bolgeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahmin_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afet_olayi_id', sa.Integer(), nullable=False),
    sa.Column('acil_barinma', sa.Integer(), nullable=False),
    sa.Column('gida', sa.Integer(), nullable=False),
    sa.Column('su', sa.Integer(), nullable=False),
    sa.Column('medikal', sa.Integer(), nullable=False),
    sa.Column('ekip', sa.Integer(), nullable=False),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['afet_olayi_id'], ['afet_olaylari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tahmin_kayitlari')
    op.drop_table('afet_olaylari')
    op.drop_table('bolgeler')
    # ### end Alembic commands ###
