"""iliskisel model - bolge ve afet olayi tablolari

Revision ID: 53f15d69de54
Revises: dcd5a1f524d1
Create Date: 2026-05-28 22:05:04.154060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f15d69de54'
down_revision = 'dcd5a1f524d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolgeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('il', sa.String(length=50), nullable=False),
    sa.Column('ilce', sa.String(length=50), nullable=True),
    sa.Column('nufus', sa.Integer(), nullable=False),
    sa.Column('koordinat_lat', sa.Float(), nullable=True),
    sa.Column('koordinat_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('afet_olaylari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bolge_id', sa.Integer(), nullable=False),
    sa.Column('deprem_buyuklugu', sa.Float(), nullable=False),
    sa.Column('bina_yikim_orani', sa.Float(), nullable=False),
    sa.Column('hava_sicakligi', sa.Float(), nullable=False),
    sa.Column('ulasim_durumu', sa.Integer(), nullable=False),
    sa.Column('yasli_nufus_orani', sa.Float(), nullable=False),
    sa.Column('olay_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bolge_id'], ['bolgeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tahmin_kayitlari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afet_olayi_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('acil_barinma', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gida', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('su', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('medikal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ekip', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_tahmin_afet_olayi', 'afet_olaylari', ['afet_olayi_id'], ['id'])
        batch_op.drop_column('nufus')
        batch_op.drop_column('barinma_sonucu')
        batch_op.drop_column('yasli_nufus_orani')
        batch_op.drop_column('gida_sonucu')
        batch_op.drop_column('ulasim_durumu')
        batch_op.drop_column('ekip_sonucu')
        batch_op.drop_column('hava_sicakligi')
        batch_op.drop_column('medikal_sonucu')
        batch_op.drop_column('bina_yikim_orani')
        batch_op.drop_column('su_sonucu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tahmin_kayitlari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('su_sonucu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('bina_yikim_orani', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('medikal_sonucu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hava_sicakligi', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('ekip_sonucu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('ulasim_durumu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('gida_sonucu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('yasli_nufus_orani', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('barinma_sonucu', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('nufus', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_tahmin_afet_olayi', type_='foreignkey')
        batch_op.drop_column('ekip')
        batch_op.drop_column('medikal')
        batch_op.drop_column('su')
        batch_op.drop_column('gida')
        batch_op.drop_column('acil_barinma')
        batch_op.drop_column('afet_olayi_id')

    op.drop_table('afet_olaylari')
    op.drop_table('bolgeler')
    # ### end Alembic commands ###
