"""Initial migration - TahminKaydi tablosu

Revision ID: dcd5a1f524d1
Revises: 
Create Date: 2026-05-28 21:49:43.488540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd5a1f524d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tahmin_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nufus', sa.Integer(), nullable=False),
    sa.Column('bina_yikim_orani', sa.Float(), nullable=False),
    sa.Column('hava_sicakligi', sa.Float(), nullable=False),
    sa.Column('ulasim_durumu', sa.Integer(), nullable=False),
    sa.Column('yasli_nufus_orani', sa.Float(), nullable=False),
    sa.Column('barinma_sonucu', sa.Integer(), nullable=False),
    sa.Column('gida_sonucu', sa.Integer(), nullable=False),
    sa.Column('su_sonucu', sa.Integer(), nullable=False),
    sa.Column('medikal_sonucu', sa.Integer(), nullable=False),
    sa.Column('ekip_sonucu', sa.Integer(), nullable=False),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tahmin_kayitlari')
    # ### end Alembic commands ###
